spring.config.import=optional:file:.env[.properties]

spring.application.name=commerce-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/commerce_lab
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET}
app.security.jwt.access-token-expiration-seconds=86400
app.security.allowed-origin=${APP_SECURITY_ALLOWED_ORIGIN}
app.security.cookie.secure=${APP_SECURITY_COOKIE_SECURE}

app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
app.cloudinary.api-key=${CLOUDINARY_API_KEY}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET}
app.cloudinary.base-folder=${CLOUDINARY_BASE_FOLDER}